/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { OrderCreateNestedManyWithoutItemsInput } from "./OrderCreateNestedManyWithoutItemsInput";
import { Type } from "class-transformer";
import { ReviewCreateNestedManyWithoutItemsInput } from "./ReviewCreateNestedManyWithoutItemsInput";

@InputType()
class ItemCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dimensions?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  weight?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  category?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutItemsInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutItemsInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutItemsInput;

  @ApiProperty({
    required: false,
    type: () => ReviewCreateNestedManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => ReviewCreateNestedManyWithoutItemsInput)
  @IsOptional()
  @Field(() => ReviewCreateNestedManyWithoutItemsInput, {
    nullable: true,
  })
  reviews?: ReviewCreateNestedManyWithoutItemsInput;
}

export { ItemCreateInput as ItemCreateInput };
